### ISSUE TITLE
"TypeError" for fins.FinsClient

### ISSUE THREAD

**Issue by pbracs** [Steve-Mcl/node-red-contrib-omron-fins#1]
Hey,
Thank you for creating the node!

My issue is this: 
Installed the node on a Node-RED docker container. Created a simple flow (Inject -> FINS Read -> Debug) to test it. When deploying the flow I get this error: "TypeError: fins.FinsClient is not a function".

This was my setup:
1. Official Node-RED Docker image (https://hub.docker.com/r/nodered/node-red)
2. FINS protocol implementation module (https://github.com/patrick--/node-omron-fins)
3. Your Omron FINS Node

![image](https://user-images.githubusercontent.com/51191779/78892032-4540f700-7a71-11ea-9bd7-d5be63477610.png)

I'm new to Node-RED so might be some mistake on my side or maybe some dependencies missing.

Hope you can help me!
Thanks!

**Comment by Steve-Mcl** [comment]
Hi, I did some refactoring before publishing & possibly broke something. I will try to get this sorted ASAP.

**Comment by Steve-Mcl** [comment]
Updated to fix the error.  Its live on [NPM](https://www.npmjs.com/package/node-red-contrib-omron-fins) now (but may take a short while to be available in the node-red library for installation.

Please test & let me know.

**Comment by pbracs** [comment]
Hi, thank you for the fast response!
Re-installed your node and now I can successfuly deploy the flow.

But when executing the flow I get another error: ""TypeError: Cannot read property 'includes' of undefined""

Could this also be linked to the refactoring?

![image](https://user-images.githubusercontent.com/51191779/78984539-2c971680-7b2f-11ea-95da-af7fe7970cbe.png)

**Comment by pbracs** [comment]
Made some adjusting to my configuration and it seems that the error was on my side.

So the issue is resolved!
Thank you!

**Comment by Steve-Mcl** [comment]
hi, I may be able to better handle this - what was the configuration issue and what did you do to fix it. 

also, can you confirm this is working as expected?  

cheers Steve.

**Comment by pbracs** [comment]
Hi,
I had a problem with the Address field. Had to change the field type from "msg" to "string".

Now, when I execute the flow I get a "timeout" response, but I think that's because my PLC is not responding correctly.
In you node information tab, it is said that "To open / close the FINS Protocol connection, send boolean true in msg.connect or msg.disconnect." Is this done through your FINS Read node or do I need to add another one (e.g. UDP node) to open the connection?

**Comment by pbracs** [comment]
Situation update: the "timeout" response was caused by misconfiguration (had the wrong port specified).
Now I have moved on to my next error: "Response is NG! endCode: 2108, endCodeDescription:Write Not Possible: Cannot change."

But the important thing is that I am getting a response from the PLC, so I can confirm that the node is working correctly.

**Comment by Steve-Mcl** [comment]
that 2108 error is often due to bad setting. 

I always try to set node dials on the PLC to the same value as last octet of IP address.  e.g. for PLC IP 192.168.0.10, node 10 (node dials 0 A) use 10 for DA1 (if you change node number dials, don't forget to power cycle the PLC) 

same for your PC IP, if IP is 192.168.0.11 then use 11 for SA1 

lastly, if your subnet mask is greater than /24 (> 255.255.255.0) then you might also have to put your PC IP in the PLC Ethernet card in the node address table. 

also, set the Combined option (I forget it's name)

these are not really stipulations of the node but of FINS protocol.

**Comment by Steve-Mcl** [comment]
sending msg.connect / disconnect can be sent to either read or write node. the PLC configuration associated with that read/write node will be connected/disconnected.

**Comment by pbracs** [comment]
Hi,
So I fixed my configuration based on your previous comments and everything works great!
Thank you for the implementation and support. :)

**Comment by MEsparcia-otaku** [comment]
I am having the same problem pbracs had...

the node fins read stays timing out when reading values, and I did not have any results yet

help, thx
