### ISSUE TITLE
NJ102 Read/Write Command Format Error (End code:1004)

### ISSUE THREAD

**Issue by Peaw** [Steve-Mcl/node-red-contrib-omron-fins#10]
I always get this node-red message (Response is NG! endCode: 1004, endCodeDescription:Command Format Error: Command format error.)

Node-red: FINS Connection node Setup
![image](https://user-images.githubusercontent.com/5587269/109618011-a716bd80-7b69-11eb-83ce-49587ad60237.png)
Node-red: Fins Read Setup
![image](https://user-images.githubusercontent.com/5587269/109618637-5d7aa280-7b6a-11eb-9a02-0774f2f21465.png)
Node-red: Fins Write Setup
![image](https://user-images.githubusercontent.com/5587269/109619293-307abf80-7b6b-11eb-8464-4fa6fca69a82.png)

PLC Setup
![image](https://user-images.githubusercontent.com/5587269/109618498-315f2180-7b6a-11eb-85cd-017b1d03ac2d.png)

After Deploy
![image](https://user-images.githubusercontent.com/5587269/109618920-b9ddc200-7b6a-11eb-944d-34ce7d65b6f5.png)
After Timestamp to Read
![image](https://user-images.githubusercontent.com/5587269/109619125-f9a4a980-7b6a-11eb-9584-61640482e3f3.png)
After Timestamp to Write
![image](https://user-images.githubusercontent.com/5587269/109619391-52744200-7b6b-11eb-91b3-72a9a4900829.png)

Please help.
Thank you for your support.

**Comment by Steve-Mcl** [comment]
Hi, most odd, I have examined your screenshots and the all look perfect.

First up...
* What OS are you running?
* What version of node-red?
* What version of node js?

Things to try...
* Did you restart PLC after settings change (especially after setting the node number)
* Try setting SA1 to 0
* Can you set the plc tag `DataTest` `AT` value to `%D0` 

Long shots...
* try setting `ICF` to `128`
* Can you check the address you entered in the read/write node is trimmed to `D0` (no spaces)
* setup the 2nd EIP port & connect to that one - see if the port makes a difference?

Also, have you setup the fins network number in the routing table? 

Using CX-integrator 
![image](https://user-images.githubusercontent.com/44235289/109627859-f7762700-7b39-11eb-89c9-97f37131986a.png)


I would recommend network 4 (as it matches the 3rd octet of the IP range)

then try setting `DNA` and `SNA` to `4`

---

failing that, could you capture some wireshark (or similar network capture) of the traffic between the node-red PC and the PLC?

---

Either way, please let me know if you get this resolved (for future readers)

**Comment by Peaw** [comment]
Dear Sir,

Thank you for your reply.

As your requested. (First up)
![image](https://user-images.githubusercontent.com/5587269/109751836-e0a30380-7c11-11eb-8a15-023c115462c2.png)

I already try these..

- [/] Did you restart PLC after settings change (especially after setting the node number)
- [/] Try setting SA1 to 0
- I set the plc tag **DataTest** to **D0** and  AT value **%d0** to **%D0**
![image](https://user-images.githubusercontent.com/5587269/109752042-42636d80-7c12-11eb-8bdf-ce4041005cd4.png)

- [/] try setting ICF to 128
- [/] Can you check the address you entered in the read/write node is trimmed to D0 (no spaces)


Please explain me more about these things.

1. Setup the 2nd EIP port & connect to that one - see if the port makes a difference? - Where is it ?

2. CX-Integrator, Please guide me how to define the setup value step by step. 
![image](https://user-images.githubusercontent.com/5587269/109753228-7b9cdd00-7c14-11eb-9a6b-e0da13e1f5c2.png)

WireShark
![image](https://user-images.githubusercontent.com/5587269/109754711-21514b80-7c17-11eb-842d-5d1b842a40c4.png)

![image](https://user-images.githubusercontent.com/5587269/109754920-8016c500-7c17-11eb-8e6f-24a758ce0b52.png)

Thank you

**Comment by Steve-Mcl** [comment]
>> Setup the 2nd EIP port & connect to that one - see if the port makes a difference? - 

>Where is it ?

Isn't there 2 Ethernet/IP ports on an nx102? 


---

For routing table...
Connect to PLC
Open routing table
Select local net
Add route of network 4  to the unit that represents the Ethernet siou 
Transfer to PLC

---

Wireshark...

A picture is not enough.  Please capture 2 things read attempt and a write attempt. Then you need to send me the wireshark file (save the dump).

**Comment by Peaw** [comment]
I don't have NJ102 selection list.

![image](https://user-images.githubusercontent.com/5587269/109771605-9597e900-7c2f-11eb-8d0b-1976d67d917e.png)

![image](https://user-images.githubusercontent.com/5587269/109771745-c2e49700-7c2f-11eb-91b9-16f9070cb293.png)

Let me find another PLC, Updates CX version. and then test it again.

I will let you know the result later.

**Comment by Peaw** [comment]
I try to setup the 2nd EIP port.

![image](https://user-images.githubusercontent.com/5587269/109780786-ea406180-7c39-11eb-92af-6b885716fc79.png)

![image](https://user-images.githubusercontent.com/5587269/109780868-faf0d780-7c39-11eb-8cc4-705abc2d1686.png)


Let see the difference, I get new NG code 2108 Write Not Possible.

![image](https://user-images.githubusercontent.com/5587269/109779983-1c9d8f00-7c39-11eb-9e18-a9389ae9ad69.png)

**Comment by Steve-Mcl** [comment]
That is closer (hopefully)

show me your node-red settings for the PLC config as they are now.  (I suspect your original settings might now work).

PS can you confirm the `node-red` computer IP is 192.168.4.179 / 255.255.255.0?

**Comment by Peaw** [comment]
![image](https://user-images.githubusercontent.com/5587269/109792730-693b9700-7c46-11eb-9e8a-082d6957bc68.png)

![image](https://user-images.githubusercontent.com/5587269/109792799-78bae000-7c46-11eb-93ec-fdb561408cba.png)

![image](https://user-images.githubusercontent.com/5587269/109792873-8ec8a080-7c46-11eb-9b05-40f5fb42d0b1.png)

![image](https://user-images.githubusercontent.com/5587269/109792907-98520880-7c46-11eb-9ae8-8a84673e5ae5.png)

I try both of network publish in SYSMAC D0=Input, D100=Output. It still not working.

Maybe I missing something about inject node ?

![image](https://user-images.githubusercontent.com/5587269/109793283-07c7f800-7c47-11eb-8d3c-d8ae1a2e1c02.png)

**Comment by Steve-Mcl** [comment]
Can you answer this...

> can you confirm the node-red computer IP is 192.168.4.179 / 255.255.255.0?

NOTE: this is where node-red runs (not necessarily the same computer where you view it)

---


> Maybe I missing something about inject node ?

As you are not using `msg.topic` or `msg.payload` in the read/write nodes, the inject is not doing anything apart from trigger the FINS node.

**Comment by Peaw** [comment]
It works now

![image](https://user-images.githubusercontent.com/5587269/109898462-e0187480-7cc6-11eb-95a4-49ab6d2ec039.png)

I follow some PLC setup by this topic #6 

![image](https://user-images.githubusercontent.com/5587269/109898690-3ab1d080-7cc7-11eb-846f-23801801073d.png)

![image](https://user-images.githubusercontent.com/5587269/109898758-54ebae80-7cc7-11eb-90df-88c6cc685259.png)

Thank you for taking the time to explain this.

**Comment by Steve-Mcl** [comment]
Glad you are sorted. 

Note, to aid you in data conversions etc I developed a partner node "node-red-contrib-buffer-parser (node) - Node-RED" https://flows.nodered.org/node/node-red-contrib-buffer-parser

This greatly simplifies things when reading 32 bit values or strings or bits.
