### ISSUE TITLE
Response is NG! endCode: 1004, endCodeDescription:Command Format Error: Command format error.

### ISSUE THREAD

**Issue by dapadk** [Steve-Mcl/node-red-contrib-omron-fins#12]
I have been using this node to connect to my NX1P2 PLC for testing and it has been working great. but now i want to start using my NX102-9020 PLC, but I'm having trouble reading any data from it. using the same settings as i used in the NX1P2 ( but changing ip addresses) did not work, after some searching and reading other posts with similar problems i tried setting up the FINS routing table in sysmac stuido but i am still constantly getting the same error (Response is NG! endCode: 1004, endCodeDescription:Command Format Error: Command format error.)
here are some screen shots of all my settings and i have a wireshark file of a read attempt if you need to look at that
![finsconnect1](https://user-images.githubusercontent.com/82881923/120276620-393a7900-c2b3-11eb-8cbc-da22b5682f1f.PNG)
![finsconnect2](https://user-images.githubusercontent.com/82881923/120276638-3f305a00-c2b3-11eb-84ca-b393357f4842.PNG)
![finsconnect3](https://user-images.githubusercontent.com/82881923/120276648-422b4a80-c2b3-11eb-958f-167161326be8.PNG)
![finsconnect5](https://user-images.githubusercontent.com/82881923/120276662-46effe80-c2b3-11eb-85fa-05d2bc880995.PNG)
![finsconnect4](https://user-images.githubusercontent.com/82881923/120276671-49525880-c2b3-11eb-92be-e87696c791b3.PNG)

any help in finding out what i am doing wrong would be appriciated

**Comment by Steve-Mcl** [comment]
Try changing to the 2nd Ethernet port. 

See issue #10  - user had same problem until he swapped over to the 2nd Ethernet port.

**Comment by dapadk** [comment]
I read that post multiple times but didn't notice that when they swapped over to port 2 they also moved the original IP address, feel pretty stupid about missing that!

It works now thank you.
![finsconnect6](https://user-images.githubusercontent.com/82881923/120298365-4f9fff00-c2ca-11eb-9d24-5f9871d24a18.PNG)

I'm a little worried that swapping the IPs on the ports might have an effect on the other nodes in the network when i eventually move these settings to the production PLC but i will cross that bridge when i come to it, thanks again.

**Comment by Steve-Mcl** [comment]
Glad it is sorted. 

Not certain why users are having a problem with port 1 on the nx102. 

I'll close this issue for now. 

Thanks for letting me know.
