### ISSUE TITLE
Node red fins node in mode NX

### ISSUE THREAD

**Issue by kfernando2001** [Steve-Mcl/node-red-contrib-omron-fins#19]
Greetings,

I'm currently developing a manufacturing flow that involves three stations. Each station operates on a distinct Omron PLC. Specifically, one station uses the NJ mode, while the other two utilize the NX mode.

Despite my efforts to establish connections to all PLCs using FINS control nodes, I've only succeeded in connecting to the NJ PLC. I would greatly appreciate any advice or recommendations to resolve this issue.

Thank you.

![WhatsApp Image 2024-01-30 at 10 30 49](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/c1d0ffd6-6565-48ab-925a-519cfc644a8f)
![WhatsApp Image 2024-01-30 at 10 29 33](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/67dc71db-8e03-41d8-a438-794ffe6f2716)
![Screenshot 2024-01-30 101646](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/2403f663-2f88-483b-bfb1-edcf9e0a17b9)
![Screenshot 2024-01-30 101625](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/f904afcf-1b90-45f9-a1f5-79a179fbb6a8)
![Screenshot 2024-01-30 101604](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/21dfe2c9-ccfe-4e04-b1dd-809480c5d1f8)
![Screenshot 2024-01-30 101549](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/d3ee6904-2aba-485f-a4a5-a2e0a5e1ca60)
![WhatsApp Image 2024-01-30 at 10 34 04](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/933790f0-ec1b-41cc-9f1e-bc006bf754ec)

**Comment by Steve-Mcl** [comment]
Hi, firstly I recommend you switch to using UDP as it is (in my experience) rock solid.

In the NX 102 units, which physical port is the fins connection? I have a distant memory of it being only possible on the top most connection. 

Unfortunately I no longer have access to any NX PLCs

**Comment by kfernando2001** [comment]
Hi Steve, thanks for the quick response; Ive been told that only Port 2 in NX PLC can be used for FINS. Also I am relatively new to UDP connections, is there anything I need to know about the settings in node-red/software/hardware different from tcp?

**Comment by Steve-Mcl** [comment]
UDP is as easy or perhaps even easier to use.

 Can you show me the setting in sysmac studio. 

IP/mask/gateway
All Fins settings

Essentially everything in this video: https://youtu.be/iSWvkmhsQN4?si=igHZH0ognpc_eapn


Also, I need the IP/MASK/GATEWAY of the Node-RED server. 




> Ive been told that only Port 2 in NX PLC can be used for FINS

I can only tell you what troubles I have witnessed. I can remember having to move the connection to the first port.

**Comment by kfernando2001** [comment]
Hi Steve, I found this video too and was able to make the nodes work! Althought I am still uncertain about what the difference between UPD and TCP is but UDP works. Please note that the connection to my PC has been established through port 2 of the PLC.

![WhatsApp Image 2024-02-01 at 09 42 24_2aa18e42](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/673244d2-6b2a-43f5-8543-ef7f1c9d6eda)
![WhatsApp Image 2024-02-01 at 09 42 43_22d995a5](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/755ea14e-98e8-451c-b0ac-262bf7a22249)
![WhatsApp Image 2024-02-01 at 09 42 01_87097928](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/fab6f3a0-e814-4ef2-96a3-267269323c10)
![WhatsApp Image 2024-02-01 at 09 43 12_8cf2c868](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/3f8a1ac7-847f-430d-80dc-24cb84c41eba)
![WhatsApp Image 2024-02-01 at 09 44 26_bab9baa5](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/f42a94bb-3156-46af-ad28-eb4c42712747)
![Screenshot 2024-01-30 101647](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/0cc62c07-29cd-4182-a573-cd042d0003ae)

**Comment by Steve-Mcl** [comment]
Glad it works for you and thanks for sharing the info - will be useful for others.

PS: UDP is the better choice IMO. TCP is slower, requiring handshakes etc, can get locked up and is sometimes finicky to get setup.

Not 100% sure why TCP would not connect for you but looking at the settings it should have. 

IIRC, sometimes you have to leave one or more of the `SNA`, `DNA`, `SA*` or `DA*` values empty or `0`. Sometimes you need to have a routing table and set the `SNA`, `DNA`, `SA*` or `DA*` values to match - it depends on `ICRTDS` (where `ICRTDS` == I Cannot Recall The Details Sorry :) Mostly due to it being 2y+ since I played with FINS and probably more like 3y since I touched an NX - sorry)

Feel free to update this thread with further details if you get TCP working (for the benefit of your memory and future readers) but IMO, UDP is the better choice here.  The FINS protocol packets contain a transaction number (SID) that ties requests and responses together, meaning the handshaking and other elements of TCP are somewhat superfluous for this protocol.

A PR to the docs/built-in help would also be welcome if you feel up to it.

Cheers.

**Comment by kfernando2001** [comment]
Hi, forgive me I meant to say both TCP AND UDP work but I was surpised that UDP worked because I didn't understand how. 
Also what do you mean by this: "A PR to the docs/built-in help would also be welcome if you feel up to it."?

**Comment by Steve-Mcl** [comment]
> Also what do you mean by this: "A PR to the docs/built-in help would also be welcome if you feel up to it."?

It means, if you are feeling generous and wish to improve this node for yourself and the everyone else, I would be happy to accept an improvement contribution by way of a [Pull Request](https://youtu.be/For9VtrQx58)

**Comment by kfernando2001** [comment]
Can I know what details you would like me to provide?

**Comment by kfernando2001** [comment]
Also Can I asks you about this error I am getting with this FINS FILL node? By what I understand, this will allow me to write a value to a register a single time, which would be perfect for my project.
![WhatsApp Image 2024-02-07 at 11 57 34_79a08ac8](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/d4a48858-02cc-4509-93df-be8e551d1cb9)
![WhatsApp Image 2024-02-07 at 11 51 21_60248034](https://github.com/Steve-Mcl/node-red-contrib-omron-fins/assets/153574113/e7ddd8c7-63a3-4ca1-b34b-fab737980eb9)

**Comment by Steve-Mcl** [comment]
FILL is for filling multiple WORD addresses with the same value. 

Each node has built in help explaining what they are for and how they work.  The FILL nodes built in help states: 
> Fill consecutive 16 bit WORD values


It looks like you are trying to write to bit 1 of W0. Read the built in help for the WRITE node

**Comment by kfernando2001** [comment]
Hi Steve, it worked when I used DM memory. I initially wanted to use this node because I believed it worked by writing a single value to a single address a SINGLE TIME, so I thought that would be cleaner, but does this function similarly to Modbus, where a single value is written to multiple addresses, starting from an initial address? Also could you point out the built in help for me please, do you mean the examples in node-red?

**Comment by Steve-Mcl** [comment]
> Also could you point out the built in help for me please, do you mean the examples in node-red


No, the help tab on the right hand sidebar of Node-RED (where the debug panel is). Most nodes have built in help. All of my nodes have built in help.
