### ISSUE TITLE
Different response types

### ISSUE THREAD

**Issue by pbracs** [Steve-Mcl/node-red-contrib-omron-fins#2]
Hi,

The node is working great! This is my question:
When reading data from my PLC, I need to read some address fields as a float or 32-bit integer. As I understand, right now every response is displayed as 16-bit integer (Uint16Array).

Is there any option in changing the response type to any of the before mentioned?

**Comment by Steve-Mcl** [comment]
Hi. 

As I use multiple PLCs and didn't want to write 32bit / float functionality into each node (it's best to keep things atomic and good at what they do) so I wrote a separate second node for handling data conversions. 

See "node-red-contrib-buffer-parser (node) - Node-RED" https://flows.nodered.org/node/node-red-contrib-buffer-parser

In essence, you pull a bunch of data from the plc in one go & convert it all in the buffer-parser node to almost any format you could wish for.  It can convert to floats, 32bit signed / unsigned, byteswapping etc etc. It can do 1 or a hundred in one go in 1 hit. 


Note this is best discussed on the node-red forum.

**Comment by Steve-Mcl** [comment]
I have updated the read.me with this info. 

Please re-open or discuss on the [node-red forum](https://discourse.nodered.org/) (tag me as `@Steve-Mcl` on the forum if you want to grab my attention :slightly_smiling_face: )
