### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by abrown36** [Steve-Mcl/node-red-contrib-omron-fins#4]
This may be a user error, as I'm quite new to Node Red. I have managed to get this to read & write tags on an NX PLC. It works great whenever I trigger it. However I seem to get the following error popping up every few seconds in my debug window. Unsure why the timeout would occur as the communications must be working to read and write the tags?

![Timeout](https://user-images.githubusercontent.com/68322592/87520098-9a2a8400-c6d6-11ea-9fa1-6aff6aa267e7.jpg)

7/15/2020, 7:52:24 PMnode: PLC
msg : string[80]
"Error connecting to PLC: Error: TIMEOUT occurred while reading Controller Props."

**Comment by Steve-Mcl** [comment]
Search your node-red flow (CTRL+F) for **Batch_PLC** to see where this is coming from.

I suspect you will find that is **NOT** the OMRON FINS node

In fact I would put money on you have installed `node-red-contrib-cip-ethernet-ip` and still have a config node setup for that library. 

Look in the node-red config nodes....

![image](https://user-images.githubusercontent.com/44235289/88319895-b51f7880-cd14-11ea-9c6b-05c44b7d60ad.png)

**Comment by Steve-Mcl** [comment]
Since I dont believe your issue is actually related to this node, I will close this issue.

Please re-open it if I am incorrect.

**Comment by ottobolyos** [comment]
> In fact I would put money on you have installed `node-red-contrib-cip-ethernet-ip` and still have a config node setup for that library.

I have encountered the very same issue and removing the config node solved this issue. Thanks! :pray:
