### ISSUE TITLE
Change Configuration on Runtime

### ISSUE THREAD

**Issue by danix3987** [Steve-Mcl/node-red-contrib-omron-fins#7]
Hello Steve,
I've tried your node with an NJ PLC and works really well. 
I would like to know if there is a way to change PLC connection config parameters on runtime.
Thank you

**Comment by Steve-Mcl** [comment]
Hi, no there is not. That is not a common use case. However, if you
describe your situation & what you are trying to achieve, there might be an
alternative solution.

**Comment by danix3987** [comment]
I'm building an application with electron and this app has to run on different systems, the user need to change ip address and SA1 DA1 values (from node-red dashboard) to point different PLCs; I have already think about modify the json flow on runtime with values inserted from dashboard and force for a reboot, but this solution cannot be achieved if I pack with asar. If there is a smarter alternative, doesn't matter if needs a reboot, will be really appreciated! Thank you for your useful job and your fast response!

**Comment by Steve-Mcl** [comment]
Hi, I cant test this right now, but you should be able to enter environment variables.

* Set environment vars in terminal or batch file or system 
* Set the IP, PORT, DNA, DA1 etc to values like this `${env_var_name}`
    *  e.g. ${PLC_IP}  for the IP address, ${PLC_DNA} for DNA, etc

If that works, then perhaps you could get node-red to somehow set system env vars?

Example using ENV variables...
![image](https://user-images.githubusercontent.com/44235289/103022166-553b3100-4543-11eb-88b2-e0a95797725d.png)

Let me know if you have success (or not).

**Comment by danix3987** [comment]
Thank you Steve! Simply works! I've tried to set environment variable and value with "setx" cmd via node red exec node and after the restart of node-red it takes the new values!

**Comment by Steve-Mcl** [comment]
no bother. glad it works.
