### ISSUE TITLE
TypeError: memoryAddress.match

### ISSUE THREAD

**Issue by serafimdasaudade** [Steve-Mcl/node-red-contrib-omron-fins#8]
I'm getting this error when I try to read any Address. 
I don't understand this error.

`TypeError: memoryAddress.match is not a function`

I think the node configuration it is OK.
This is my node-red flow:

`[
    {
        "id": "54d1a3a0.71c9bc",
        "type": "tab",
        "label": "Flow 2",
        "disabled": false,
        "info": ""
    },
    {
        "id": "1465ed0b.855aa3",
        "type": "FINS Read",
        "z": "54d1a3a0.71c9bc",
        "name": "",
        "connection": "39eebefb.ac07d2",
        "addressType": "msg",
        "address": "topic",
        "countType": "num",
        "count": 1,
        "msgPropertyType": "msg",
        "msgProperty": "payload",
        "outputFormatType": "list",
        "outputFormat": "buffer",
        "x": 510,
        "y": 120,
        "wires": [
            []
        ]
    },
    {
        "id": "474a8c10.b67af4",
        "type": "inject",
        "z": "54d1a3a0.71c9bc",
        "name": "",
        "props": [
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "connect",
        "x": 180,
        "y": 80,
        "wires": [
            [
                "1465ed0b.855aa3"
            ]
        ]
    },
    {
        "id": "f585fb4d.5fe198",
        "type": "inject",
        "z": "54d1a3a0.71c9bc",
        "name": "",
        "props": [
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "D100",
        "x": 150,
        "y": 160,
        "wires": [
            [
                "1465ed0b.855aa3"
            ]
        ]
    },
    {
        "id": "840a866e.074658",
        "type": "FINS Write",
        "z": "54d1a3a0.71c9bc",
        "name": "",
        "connection": "39eebefb.ac07d2",
        "addressType": "msg",
        "address": "topic",
        "dataType": "msg",
        "data": "payload",
        "msgPropertyType": "msg",
        "msgProperty": "payload",
        "x": 530,
        "y": 260,
        "wires": [
            []
        ]
    },
    {
        "id": "e66f7f2f.da065",
        "type": "inject",
        "z": "54d1a3a0.71c9bc",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "D100",
        "payload": "1",
        "payloadType": "num",
        "x": 150,
        "y": 260,
        "wires": [
            [
                "840a866e.074658"
            ]
        ]
    },
    {
        "id": "39eebefb.ac07d2",
        "type": "FINS Connection",
        "name": "",
        "host": "192.168.200.11",
        "port": "9600",
        "MODE": "CSCJ",
        "ICF": "0x80",
        "DNA": "11",
        "DA1": "11",
        "DA2": "0",
        "SNA": "0",
        "SA1": "100",
        "SA2": "0"
    }
]`

Best Regards,

**Comment by Steve-Mcl** [comment]
Hi, there doesnt appear to be any issue with your flow (looks correct)



`memoryAddress.match` is not part of my code - the closest i can see is [this](https://github.com/Steve-Mcl/node-omron-fins/blob/c5a6121a9d847a9a0cb23bf8755de321884ed120/lib/fins_client.js#L265) in the omron driver code.

I **can** however find `memoryAddress.match` in another `fin_client` code [here](https://github.com/ptrks/node-omron-fins/blob/6435dfdcfa4754fdb537a5787643066c3e5be47b/lib/fins_client.js#L75) which leads me to suspect something a-miss with your installation. 

#### Have installed any other omron PLC related stuff (either manually through NPM or through the node-red pallete)? 

You should remove any / all "Omron PLC" related nodes you are not using, ensure firectory `node_modules\omron-fins` is deleted then re-install `node-red-contrib-omron-fins` 

PS, I use this node in a production environment (24/7) and I know of a few others using. It is very reliable.

**Comment by serafimdasaudade** [comment]
Tks, 
yes you are correct. That was another omron-fins lib. 

Best Regards,
