### ISSUE TITLE
Machine with CJ1M - ETN PLC stop working.

### ISSUE THREAD

**Issue by serafimdasaudade** [Steve-Mcl/node-red-contrib-omron-fins#9]
Hi,
I'm testing this node-red module on a production machine.
![thumbnail_IMG_7831](https://user-images.githubusercontent.com/8669441/107927955-9cf09e80-6f6f-11eb-86ad-5a324f31d938.jpg)

![thumbnail_IMG_7824](https://user-images.githubusercontent.com/8669441/107929157-2ce31800-6f71-11eb-8581-76dcad6f4a17.jpg)

I can read the PLC Memory Address. But something strange happens when the machine start is production. 

For example, the machine is running and I start reading PLC Memory address D3336 every second. After some time the machine stop working. When this happen the machine don't report any alarm or event. To Resume the production I need to stop the reading and do a power off/on on the PLC. 

I don't understand what is the problem. Maybe I need to change the PLC configs ?

![Screenshot_20210212_163047](https://user-images.githubusercontent.com/8669441/107928911-d7a70680-6f70-11eb-9fe3-bc2ac9a12ddd.png)
 

Best Regards,

**Comment by Steve-Mcl** [comment]
Hi, we use this extensively without issue so something odd is going on.  I have in my many years seen an ETN "misbehave" (but that is 1 out of approx 50 we have on site) (we mostly use EIP21 cards now)

I am curious to why there is no IP address set? Could you connect to PLC and click **"Transfer [Unit to PC]"** and show me your settings? once i see actual settings i will advise on best settings for your Ethernet Card.

Also, do you have a local routing table set for this UNIT? (what FINS network address is set?)

PS what else is communicating with the ETN? 

Lastly, if necessary, do you have another ETN or EIP card you could install?

**Comment by serafimdasaudade** [comment]
OK, Tks Steve,
Will try to get this info. In the following days I will go to the factory.

Best Regards,

**Comment by Steve-Mcl** [comment]
After 14 days of silence, I will assume you have resolved this & close this. 

Re-open the issue if you need to.

cheers.
